name: Build Gatsby site

on:
  pull_request:
    branches:
     - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --prod --pure-lockfile

      - name: Build
        run: yarn run build

        
